services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant-configuration/configuration.yaml:/config/configuration.yaml
      - /etc/localtime:/etc/localtime:ro  # Linux hosts only
    restart: unless-stopped
    privileged: true
    network_mode: host
