
# Loads default set of integrations. Do not remove.
default_config:

recorder:
  # Using pymsql for installations in virtual environments
  db_url: mysql+pymysql://root:password@134.209.139.189/homeassistant?charset=utf8mb4
  #db_url: rqlite+pyrqlite://root:password@15.160.176.27:4001/