
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 172.18.0.0/24

binary_sensor:
  - platform: rest
    name: usbrelay1
    resource: http://192.168.0.137:8000/1/status
    method: GET
    value_template: '{{ value_json.status }}'

  - platform: rest
    name: usbrelay2
    resource: http://192.168.0.137:8000/2/status
    method: GET
    value_template: '{{ value_json.status }}'

  - platform: rest
    name: usbrelay3
    resource: http://192.168.0.137:8000/3/status
    method: GET
    value_template: '{{ value_json.status }}'

  - platform: rest
    name: usbrelay4
    resource: http://192.168.0.137:8000/4/status
    method: GET
    value_template: '{{ value_json.status }}'

  - platform: rest
    name: usbrelay5
    resource: http://192.168.0.137:8000/5/status
    method: GET
    value_template: '{{ value_json.status }}'

  - platform: rest
    name: usbrelay6
    resource: http://192.168.0.137:8000/6/status
    method: GET
    value_template: '{{ value_json.status }}'

  - platform: rest
    name: usbrelay7
    resource: http://192.168.0.137:8000/7/status
    method: GET
    value_template: '{{ value_json.status }}'

  - platform: rest
    name: usbrelay8
    resource: http://192.168.0.137:8000/8/status
    method: GET
    value_template: '{{ value_json.status }}'

rest_command:
  usbrelay1_on:
    url: "http://192.168.0.137:8000/1/on"
    method: POST
  usbrelay1_off:
    url: "http://192.168.0.137:8000/1/off"
    method: POST
  usbrelay2_on:
    url: "http://192.168.0.137:8000/2/on"
    method: POST
  usbrelay2_off:
    url: "http://192.168.0.137:8000/2/off"
    method: POST
  usbrelay3_on:
    url: "http://192.168.0.137:8000/3/on"
    method: POST
  usbrelay3_off:
    url: "http://192.168.0.137:8000/3/off"
    method: POST
  usbrelay4_on:
    url: "http://192.168.0.137:8000/4/on"
    method: POST
  usbrelay4_off:
    url: "http://192.168.0.137:8000/4/off"
    method: POST
  usbrelay5_on:
    url: "http://192.168.0.137:8000/5/on"
    method: POST
  usbrelay5_off:
    url: "http://192.168.0.137:8000/5/off"
    method: POST
  usbrelay6_on:
    url: "http://192.168.0.137:8000/6/on"
    method: POST
  usbrelay6_off:
    url: "http://192.168.0.137:8000/6/off"
    method: POST
  usbrelay7_on:
    url: "http://192.168.0.137:8000/7/on"
    method: POST
  usbrelay7_off:
    url: "http://192.168.0.137:8000/7/off"
    method: POST
  usbrelay8_on:
    url: "http://192.168.0.137:8000/8/on"
    method: POST
  usbrelay8_off:
    url: "http://192.168.0.137:8000/8/off"
    method: POST

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: disk_use
      - type: disk_free
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: swap_use_percent
      - type: swap_use
      - type: swap_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0
      - type: packets_in
        arg: eth0
      - type: packets_out
        arg: eth0
      - type: ipv4_address
        arg: eth0
      - type: ipv6_address
        arg: eth0
      - type: processor_use
      - type: processor_temperature
      - type: last_boot