esphome:
  name: esp-growbox

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "ap-grow"
  password: "12345678"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Growbox Fallback Hotspot"
    password: "6SSRU2K298nO"

captive_portal:
    