esphome:
  name: esp-growbox
  libraries:
    - "Wire"
    - "uFire SHT20"
    - "ArduinoJson"
  includes:
    - sht20.h

esp8266:
  board: esp01_1m

# A global variable that stores the "non-resettable" pulse counter
globals:
  - id: water_offset
    type: float
    restore_value: true  # persists on reboot
    initial_value: "0.0"

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: reset_water_counter
      then:
        # Set offset = raw counter
        - lambda: id(water_offset) = id(water_volume_counter_raw).state;
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.199
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_wifi_ssid
    password: !secret fallback_wifi_password

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

output:
  - platform: esp8266_pwm
    pin: GPIO15
    id: pwm_output
    inverted: true

fan:
  - platform: speed
    output: pwm_output
    name: "Inline Fan"

sensor:
  # Reference: https://esphome.io/components/sensor/pulse_counter.html
  # The main pulse_counter sensor for reading pulses
  - platform: pulse_counter
    pin:
      number: GPIO12
      # Enable internal pull-up resistor for stable readings
      mode:
        input: true
        pullup: true
    #internal: true
    icon: "mdi:water"
    name: "Water flow rate"
    id: water_usage_meter
    # Interval to update the flow rate sensor data
    update_interval: 5s
    # update_interval: 60s  # Use this for calibration

    # Calibration constant (K) = 1596.35635625 pulses per liter
    # Pulses every 5 seconds -> L/min
    # = pulses(5s) * (60/5) / 1596.35635625
    # ~ pulses(5s) * 0.0075171185637956
    filters:
      - multiply: 0.0075171185637956

    # Create a resettable entity that accumulates total pulses
    # This sensor can be reset via the Home Assistant service: counter.reset
    total:
      name: "Total used water"
      id: water_volume_counter_raw
      unit_of_measurement: "L"
      accuracy_decimals: 3
      device_class: "volume"
      state_class: "total_increasing"
      filters:
        # 1:1596.35635625
        - multiply: 0.00062642654
  - platform: template
    name: "Total used water (resettable)"
    id: water_volume_counter_resettable
    unit_of_measurement: "L"
    accuracy_decimals: 3
    device_class: "volume"
    state_class: "total_increasing"
    icon: "mdi:water"
    lambda: |-
      // Return the difference between raw counter and offset
      return id(water_volume_counter_raw).state - id(water_offset);
  - platform: mhz19
    co2:
      name: "CO2"
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 60s
    automatic_baseline_calibration: false
  - platform: dht
    pin: GPIO4
    model: AM2302
    temperature:
      name: "Air temperature"
    humidity:
      name: "Air humidity"
      accuracy_decimals: 2
    update_interval: 60s
  - platform: bme280
    temperature:
      name: "Air Temperature"
      oversampling: 16x
    pressure:
      name: "Air Pressure"
    humidity:
      name: "Air Humidity"
    address: 0x77
    update_interval: 60s
  - platform: custom
    lambda: |-
      auto sht20 = new SHT20();
      App.register_component(sht20);
      return {sht20->temperature_sensor, sht20->humidity_sensor, sht20->vpd_sensor, sht20->dew_point_sensor};
    sensors:
      - name: "Soil Temperature"
        id: sensor_soil_temperature
        unit_of_measurement: °C
        accuracy_decimals: 2
      - name: "Soil Humidity"
        id: sensor_soil_humidity
        unit_of_measurement: "%"
        accuracy_decimals: 2
      - name: "Soil Vapour-pressure deficit"
        id: sensor_vpd
        unit_of_measurement: "kPa"
        accuracy_decimals: 2
      - name: "Soil Dew point"
        id: sensor_soil_dew_point
        unit_of_measurement: °C
        accuracy_decimals: 2

captive_portal:
