esphome:
  name: esp-growbox
  libraries:
    - "Wire"
    - "uFire SHT20"
    - "ArduinoJson"
  includes:
    - sht20.h

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.199
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_wifi_ssid
    password: !secret fallback_wifi_password

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

output:
  - platform: esp8266_pwm
    pin: GPIO15
    id: pwm_output
    inverted: true

fan:
  - platform: speed
    output: pwm_output
    name: "Inline Fan"

button:
  - platform: template
    name: "Reset Water Usage"
    on_press:
      - sensor.integration.reset: total_water_usage

# References: 
# - https://esphome.io/components/sensor/pulse_counter.html
# - https://esphome.io/components/sensor/integration
sensor:
  - platform: integration
    name: "Total Water Usage"
    sensor: water_usage_meter
    id: total_water_usage
    time_unit: "min"
    unit_of_measurement: "L"
    state_class: "total_increasing"
    device_class: "volume"
    accuracy_decimals: 3
    restore: true

  - platform: pulse_counter
    pin:
      number: GPIO12
      # Enable internal pull-up resistor for stable readings
      mode:
        input: true
        pullup: true
    #internal: true
    icon: "mdi:water"
    name: "Water flow rate"
    id: water_usage_meter
    unit_of_measurement: "L/min"
    state_class: "measurement"
    device_class: "volume_flow_rate"
    update_interval: 60s
    accuracy_decimals: 4
    filters:
      # Convert pulses/min to L/min
      # Calibration constant = 1596.35635625
      # Each pulse corresponds to 1/1596 liters = 0.000626 L
      - multiply: 0.000626

  - platform: template
    name: "Total used water (resettable)"
    id: water_volume_counter_resettable
    unit_of_measurement: "L"
    accuracy_decimals: 3
    device_class: "volume"
    state_class: "total_increasing"
    icon: "mdi:water"
    lambda: |-
      // Return the difference between raw counter and offset
      return id(water_volume_counter_raw).state - id(water_offset);
  
  - platform: mhz19
    co2:
      name: "CO2"
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 60s
    automatic_baseline_calibration: false
  
  - platform: dht
    pin: GPIO4
    model: AM2302
    temperature:
      name: "Air temperature"
    humidity:
      name: "Air humidity"
      accuracy_decimals: 2
    update_interval: 60s
  
  - platform: bme280
    temperature:
      name: "Air Temperature"
      oversampling: 16x
    pressure:
      name: "Air Pressure"
    humidity:
      name: "Air Humidity"
    address: 0x77
    update_interval: 60s
  
  - platform: custom
    lambda: |-
      auto sht20 = new SHT20();
      App.register_component(sht20);
      return {sht20->temperature_sensor, sht20->humidity_sensor, sht20->vpd_sensor, sht20->dew_point_sensor};
    sensors:
      - name: "Soil Temperature"
        id: sensor_soil_temperature
        unit_of_measurement: °C
        accuracy_decimals: 2
      - name: "Soil Humidity"
        id: sensor_soil_humidity
        unit_of_measurement: "%"
        accuracy_decimals: 2
      - name: "Soil Vapour-pressure deficit"
        id: sensor_vpd
        unit_of_measurement: "kPa"
        accuracy_decimals: 2
      - name: "Soil Dew point"
        id: sensor_soil_dew_point
        unit_of_measurement: °C
        accuracy_decimals: 2

captive_portal:
