
# Loads default set of integrations. Do not remove.
default_config:


# For connecting to an external database
recorder:
  # Use pymsql for installations in virtual environments and MySQL/MariaDB databases
  db_url: mysql://root:password@188.166.134.95/homeassistant_docker?charset=utf8mb4
  #db_url: rqlite+pyrqlite://root:password@15.160.176.27:4001/  # for rqlite database

