esphome:
  name: esp-growbox
  friendly_name: esp-growbox

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "pV6FGiSsr/VwD7/NZEMLPFB3/h0H3uuwiimo6oa7U00="

ota:
  password: "c207fa2ce1f5a041a895bf19b96f7eb9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Growbox Fallback Hotspot"
    password: "1jgHz7C7Oz4i"

captive_portal:
    