esphome:
  name: esp-growbox
  friendly_name: esp-growbox

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8eLiqnRkrXoAfFTGrhcb5Iww6RPERar8YgViwYbN2OA="

ota:
  password: "3ac9ebb18c88e8d146e6602bca2b87e7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Growbox Fallback Hotspot"
    password: "v7HGxp1QkGsS"

captive_portal:
    